Added log function

diff --git a/Limitator/limitator b/Limitator/limitator
--- a/Limitator/limitator
+++ b/Limitator/limitator
@@ -123,6 +123,13 @@ function file_Creation(){
         echo "file expire.sh already exist."
         echo "# Deleting expire.sh"
         sudo rm -f $ENV_VAR_DIR$ENV_VAR_FILE
+        if [[ $? -eq 0 ]]; then
+            echo "# expire.sh deleted successfully"
+            echo 10; sleep 2
+        else
+            echo "Err:3x002 => Failed to remove expire.sh, make sure you are running this script as root or with sudo" 1>$LOG_DIR$LOG_FILE 2>&1
+            exit 1
+        fi
         echo 10; sleep 2
         echo "# Creating new expire.sh file"
         sudo touch $ENV_VAR_DIR$ENV_VAR_FILE
@@ -243,6 +250,9 @@ function year_Check(){
 function service_Creation(){
     ## Create the timeout.service file in /etc/systemd/system/ if it doesn't exist
     (
+    echo "# Installing notify-osd..."
+    sudo apt update && sudo apt install notify-osd -y 1>$LOG_DIR$LOG_FILE 2>&1
+
     if [[ -f $SYSTEMD_DIR/timeout.service ]]; then
         echo "Le fichier timeout.service existe déjà."
         echo "# Suppression du fichier timeout.service"
@@ -280,7 +290,7 @@ function service_Creation(){
         --auto-close
 }
 
-function scriptsEncription(){
+function scripts_Encription(){
     zenity --question \
         --title="Limitator" \
         --text="The scripts will now be encrypted, are you sure you want to continue ? (You won't be able to edit the script once this is done)" \
@@ -371,11 +381,111 @@ function script_Directory_Creation(){
         --auto-close
 }
 
+# purpose: to pass msgs and print them to a log file and terminal
+#  - with datetime
+#  - the type of msg - INFO, ERROR, DEBUG, WARNING
+# usage:
+# do_log "INFO some info message"
+# do_log "ERROR some error message"
+# do_log "DEBUG some debug message"
+# do_log "WARNING some warning message"
+# depts:
+#  - PRODUCT_DIR - the root dir of the sfw project
+#  - PRODUCT - the name of the software project dir
+#  - host_name - the short hostname of the host / container running on
+# 
+# from : Yordan Georgiev (stackoverflow)
+#------------------------------------------------------------------------------
+do_log(){
+
+  print_ok() {
+      GREEN_COLOR="\033[0;32m"
+      DEFAULT="\033[0m"
+      echo -e "${GREEN_COLOR} ✔ [OK] ${1:-} ${DEFAULT}"
+  }
+
+  print_warning() {
+      YELLOW_COLOR="\033[33m"
+      DEFAULT="\033[0m"
+      echo -e "${YELLOW_COLOR} ⚠ ${1:-} ${DEFAULT}"
+  }
+
+   print_info() {
+      BLUE_COLOR="\033[0;34m"
+      DEFAULT="\033[0m"
+      echo -e "${BLUE_COLOR} ℹ ${1:-} ${DEFAULT}"
+  }
+
+  print_fail() {
+      RED_COLOR="\033[0;31m"
+      DEFAULT="\033[0m"
+      echo -e "${RED_COLOR} ❌ [NOK] ${1:-}${DEFAULT}"
+  }
+
+  type_of_msg=$(echo $*|cut -d" " -f1)
+  msg="$(echo $*|cut -d" " -f2-)"
+  log_dir="${PRODUCT_DIR:-}/dat/log/bash" ; mkdir -p $log_dir
+  log_file="$log_dir/${PRODUCT:-}."$(date "+%Y%m%d")'.log'
+  msg=" [$type_of_msg] `date "+%Y-%m-%d %H:%M:%S %Z"` [${PRODUCT:-}][@${host_name:-}] [$$] $msg "
+  case "$type_of_msg" in
+    'FATAL') print_fail "$msg" | tee -a $log_file ;;
+    'ERROR') print_fail "$msg" | tee -a $log_file ;;
+    'WARNING') print_warning "$msg" | tee -a $log_file ;;
+    'INFO') print_info "$msg" | tee -a $log_file ;;
+    'OK') print_ok "$msg" | tee -a $log_file ;;
+    *) echo "$msg" | tee -a $log_file ;;
+  esac
+
+}
+
 log_Creation
+if [[ $? -eq 0 ]]; then
+    do_log "OK 0x000 => Log Created successfuly!" 1>$LOG_DIR$LOG_FILE 2>&1
+else
+    do_log "ERROR Err:0x001 => Failed to create log files. Make sure you have the proper privileges to run this script." 1>$LOG_DIR$LOG_FILE 2>&1
+    exit 1
+fi
 check_Internet_Connection
+if [[ $? -eq 0 ]]; then
+    do_log "OK 1x000 => This system is connected to the internet" 1>$LOG_DIR$LOG_FILE 2>&1
+else
+    do_log "FATAL Err:1x001 => Internet connection Failed, Make sure you are connected to internet before running this script" 1>$LOG_DIR$LOG_FILE 2>&1
+    exit 1
+fi
 year_Check
+if [[ $? -eq 0 ]]; then
+    do_log "OK 2x000 => NTP synchronisation is working." 1>$LOG_DIR$LOG_FILE 2>&1
+else
+    do_log "FATAL Err:2x001 => Couldn't reach any NTP server for time synchronisation, make sure you are connected to internet before running this script" 1>$LOG_DIR$LOG_FILE 2>&1
+    exit 1
+fi
 file_Creation
-scriptsEncription
+if [[ $? -eq 0 ]]; then
+    do_log "OK 3x000 => This system is connected to the internet" 1>$LOG_DIR$LOG_FILE 2>&1
+
+else
+    do_log "ERROR Err:3x001 => Internet connection Failed, Make sure you are connected to internet before running this script" 1>$LOG_DIR$LOG_FILE 2>&1
+    exit 1
+fi
+scripts_Encription
+if [[ $? -eq 0 ]]; then
+    do_log "OK 4x000 => Scripts have been encrypted !" 1>$LOG_DIR$LOG_FILE 2>&1
+else
+    do_log "FATAL Err:4x001 => Script encryption failed, Please refer to the README File for more information on this error" 1>$LOG_DIR$LOG_FILE 2>&1
+    exit 1
+fi
 script_Directory_Creation
+if [[ $? -eq 0 ]]; then
+    do_log "OK 5x000 => $SCRIPT_DEST_DIR successfuly created" 1>$LOG_DIR$LOG_FILE 2>&1
+else
+    do_log "ERROR Err:5x001 => Failed to create $SCRIPT_DEST_DIR, make sure you you have the proper privileges to run this script." 1>$LOG_DIR$LOG_FILE 2>&1
+    exit 1
+fi
 service_Creation
+if [[ $? -eq 0 ]]; then
+    do_log "OK 6x000 => Timeout.Service created Successfully" 1>$LOG_DIR$LOG_FILE 2>&1
+else
+    do_log "ERROR Err:6x001 => Error during Timeout.Service Creation, Please refer to the README File for more information on this error" 1>$LOG_DIR$LOG_FILE 2>&1
+    exit 1
+fi
 display_Result
